import type { PlayerFormId } from './player_types';

export const PLAYER_START_FORM: PlayerFormId = 'ball';

export const PLAYER_PLACEHOLDER_RADIUS = 20;
export const PLAYER_PLACEHOLDER_FILL_COLOR = 0x42a5f5;
export const PLAYER_PLACEHOLDER_STROKE_COLOR = 0xe3f2fd;
export const PLAYER_FORM_TRIANGLE_WIDTH = 42;
export const PLAYER_FORM_TRIANGLE_HEIGHT = 38;
export const PLAYER_FORM_SQUARE_SIZE = 36;
export const PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD = 0;
export const PLAYER_TRIANGLE_GROUNDED_ORIENTATIONS_RAD = [
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD,
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD + ((Math.PI * 2) / 3),
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD - ((Math.PI * 2) / 3)
] as const;
export const PLAYER_TRIANGLE_GROUNDED_SETTLE_LERP_SPEED = 28;
export const PLAYER_TRIANGLE_AIRBORNE_PASSIVE_SPIN_RAD_PER_SEC = Math.PI * 0.85;
export const PLAYER_TRIANGLE_AIRBORNE_CONTROLLED_SPIN_RAD_PER_SEC = Math.PI * 2.35;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_ACCEL_RAD_PER_SEC_SQ = Math.PI * 14;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_DECEL_RAD_PER_SEC_SQ = Math.PI * 11;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_MAX_RAD_PER_SEC = Math.PI * 2.7;
export const PLAYER_TRIANGLE_JUMP_VELOCITY = -670;
export const PLAYER_TRIANGLE_JUMP_CUT_MULTIPLIER = 0.48;
export const PLAYER_TRIANGLE_DASH_SPEED = 820;
export const PLAYER_TRIANGLE_DASH_DURATION_MS = 130;
export const PLAYER_TRIANGLE_DASH_COOLDOWN_MS = 260;
export const PLAYER_TRIANGLE_DASH_GROUND_CONTACT_EPSILON = 0.25;
export const PLAYER_TRIANGLE_DASH_MAX_CHARGES = 3;
export const PLAYER_TRIANGLE_CHARGES_RESTORE_DELAY_MS = 220;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_RADIUS = 4;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_OUTWARD_OFFSET = 4;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_IDLE_ALPHA = 0.42;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_ACTIVE_ALPHA = 0.96;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_IDLE_SCALE = 1;
export const PLAYER_TRIANGLE_LEADING_CORNER_MARKER_ACTIVE_SCALE = 1.3;

export const PLAYER_GROUND_MOVE_SPEED = 260;
export const PLAYER_GROUND_MOVE_ACCEL = 9000;
export const PLAYER_GROUND_MOVE_DECEL = 12000;
export const PLAYER_AIR_MOVE_SPEED = 240;
export const PLAYER_AIR_MOVE_ACCEL = 3600;
export const PLAYER_AIR_MOVE_DECEL = 700;
export const PLAYER_AIR_WIND_INFLUENCE_MULTIPLIER = 1.45;
export const PLAYER_AIR_WIND_RESPONSE = 5200;
export const PLAYER_AIR_WIND_MIN_DRIFT_RATIO = 0.2;
export const PLAYER_GRAVITY_Y = 1800;
export const PLAYER_JUMP_VELOCITY = -620;
export const PLAYER_JUMP_CUT_MULTIPLIER = 0.45;
export const PLAYER_BALL_BOOST_SPEED = 520;
export const PLAYER_BALL_BOOST_COOLDOWN_MS = 300;
export const PLAYER_BALL_BOOST_HOLD_MOVE_SPEED = 420;
export const PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED = 320;
export const PLAYER_BALL_BOOST_HOLD_ACCEL = 12000;
export const PLAYER_BALL_REBOUND_MIN_APPROACH_SPEED = 520;
export const PLAYER_BALL_REBOUND_FULL_APPROACH_SPEED = 980;
export const PLAYER_BALL_REBOUND_MIN_JUMP_VELOCITY = -700;
export const PLAYER_BALL_REBOUND_MAX_JUMP_VELOCITY = -900;
export const PLAYER_BALL_REBOUND_LANDING_WINDOW_MS = 70;

export const PLAYER_TIMER_DEFAULT_COYOTE_MS = 110;
export const PLAYER_TIMER_DEFAULT_JUMP_BUFFER_MS = 120;
export const PLAYER_TIMER_DEFAULT_TRANSFORM_LOCK_MS = 150;
export const PLAYER_TIMER_DEFAULT_DEATH_PAUSE_MS = 250;
