import type { PlayerFormId } from './player_types';

export const PLAYER_START_FORM: PlayerFormId = 'ball';

export const PLAYER_PLACEHOLDER_RADIUS = 20;
export const PLAYER_PLACEHOLDER_FILL_COLOR = 0x42a5f5;
export const PLAYER_PLACEHOLDER_STROKE_COLOR = 0xe3f2fd;

export const PLAYER_GROUND_MOVE_SPEED = 260;
export const PLAYER_GROUND_MOVE_ACCEL = 9000;
export const PLAYER_GROUND_MOVE_DECEL = 12000;
export const PLAYER_AIR_MOVE_SPEED = 240;
export const PLAYER_AIR_MOVE_ACCEL = 3600;
export const PLAYER_AIR_MOVE_DECEL = 700;
export const PLAYER_GRAVITY_Y = 1800;
export const PLAYER_JUMP_VELOCITY = -620;
export const PLAYER_JUMP_CUT_MULTIPLIER = 0.45;
export const PLAYER_BALL_BOOST_SPEED = 520;
export const PLAYER_BALL_BOOST_COOLDOWN_MS = 300;
export const PLAYER_BALL_BOOST_HOLD_MOVE_SPEED = 420;
export const PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED = 320;
export const PLAYER_BALL_BOOST_HOLD_ACCEL = 12000;

export const PLAYER_TIMER_DEFAULT_COYOTE_MS = 110;
export const PLAYER_TIMER_DEFAULT_JUMP_BUFFER_MS = 120;
export const PLAYER_TIMER_DEFAULT_TRANSFORM_LOCK_MS = 150;
export const PLAYER_TIMER_DEFAULT_DEATH_PAUSE_MS = 250;
