import type { PlayerFormId } from './player_types';
import type { PlayerTuningRawSnapshot } from './tuning/player_tuning_types';

export const PLAYER_START_FORM: PlayerFormId = 'ball';

export const PLAYER_PLACEHOLDER_RADIUS = 20;
export const PLAYER_PLACEHOLDER_FILL_COLOR = 0x42a5f5;
export const PLAYER_PLACEHOLDER_STROKE_COLOR = 0xe3f2fd;
export const PLAYER_BALL_VISUAL_STROKE_WIDTH = 2;
export const PLAYER_BALL_VISUAL_BOOST_STROKE_WIDTH = 5;
export const PLAYER_FORM_TRIANGLE_WIDTH = 42;
export const PLAYER_FORM_TRIANGLE_HEIGHT = 38;
export const PLAYER_FORM_SQUARE_SIZE = 36;
export const PLAYER_SQUARE_BODY_SIZE = PLAYER_FORM_SQUARE_SIZE;
export const PLAYER_SQUARE_VISUAL_STROKE_COLOR = 0xffffff;
export const PLAYER_SQUARE_VISUAL_ATTACH_STROKE_COLOR = 0x66bb6a;
export const PLAYER_SQUARE_VISUAL_REGEN_STROKE_COLOR = 0x42a5f5;
export const PLAYER_SQUARE_VISUAL_REGEN_STROKE_WIDTH = 5;
export const PLAYER_SQUARE_ATTACH_HOLD_STICK_SPEED = 48;
export const PLAYER_SQUARE_EDGE_DOWN_POSE_RAD = 0;
export const PLAYER_SQUARE_GROUNDED_ORIENTATIONS_RAD = [
    PLAYER_SQUARE_EDGE_DOWN_POSE_RAD,
    PLAYER_SQUARE_EDGE_DOWN_POSE_RAD + (Math.PI * 0.5),
    PLAYER_SQUARE_EDGE_DOWN_POSE_RAD + Math.PI,
    PLAYER_SQUARE_EDGE_DOWN_POSE_RAD - (Math.PI * 0.5)
] as const;
export const PLAYER_SQUARE_GROUNDED_SETTLE_LERP_SPEED = 24;
export const PLAYER_SQUARE_TRAIL_STROKE_COLOR = 0x7dd3fc;
export const PLAYER_SQUARE_TRAIL_STROKE_ALPHA = 0.95;
export const PLAYER_SQUARE_TRAIL_STROKE_WIDTH = 5;
export const PLAYER_SQUARE_TRAIL_MIN_SEGMENT_LENGTH = 6;
export const PLAYER_SQUARE_TRAIL_REATTACH_SNAP_DISTANCE = 10;
export const PLAYER_SQUARE_TRAIL_MAX_SEGMENTS = 2400;
export const PLAYER_SQUARE_TRAIL_DETACHED_FALL_SPEED = 90;
export const PLAYER_SQUARE_TRAIL_DETACHED_DISSOLVE_DURATION_SEC = 2.4;
export const PLAYER_SQUARE_TRAIL_DETACHED_REFUND_RATE = 1 / PLAYER_SQUARE_TRAIL_DETACHED_DISSOLVE_DURATION_SEC;
export const PLAYER_SQUARE_TRAIL_DETACHED_CLEANUP_ALPHA = 0.02;
export const PLAYER_SQUARE_TRAIL_BAR_WIDTH = 220;
export const PLAYER_SQUARE_TRAIL_BAR_HEIGHT = 12;
export const PLAYER_SQUARE_TRAIL_BAR_SCREEN_X = 24;
export const PLAYER_SQUARE_TRAIL_BAR_SCREEN_Y = 60;
export const PLAYER_TRIANGLE_BODY_PROXY_WIDTH = 30;
export const PLAYER_TRIANGLE_BODY_PROXY_HEIGHT = 34;
export const PLAYER_BALL_HAZARD_RADIUS = PLAYER_PLACEHOLDER_RADIUS;
export const PLAYER_SQUARE_HAZARD_SIZE = PLAYER_FORM_SQUARE_SIZE;
export const PLAYER_TRIANGLE_HAZARD_WIDTH = PLAYER_FORM_TRIANGLE_WIDTH;
export const PLAYER_TRIANGLE_HAZARD_HEIGHT = PLAYER_FORM_TRIANGLE_HEIGHT;
export const PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD = 0;
export const PLAYER_TRIANGLE_GROUNDED_ORIENTATIONS_RAD = [
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD,
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD + ((Math.PI * 2) / 3),
    PLAYER_TRIANGLE_EDGE_DOWN_POSE_RAD - ((Math.PI * 2) / 3)
] as const;
export const PLAYER_TRIANGLE_GROUNDED_SETTLE_LERP_SPEED = 28;
export const PLAYER_TRIANGLE_AIRBORNE_PASSIVE_SPIN_RAD_PER_SEC = Math.PI * 0.85;
export const PLAYER_TRIANGLE_AIRBORNE_CONTROLLED_SPIN_RAD_PER_SEC = Math.PI * 2.35;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_ACCEL_RAD_PER_SEC_SQ = Math.PI * 14;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_DECEL_RAD_PER_SEC_SQ = Math.PI * 11;
export const PLAYER_TRIANGLE_AIRBORNE_SPIN_MAX_RAD_PER_SEC = Math.PI * 2.7;
export const PLAYER_TRIANGLE_DASH_SPEED = 820;
export const PLAYER_TRIANGLE_DASH_DURATION_MS = 130;
export const PLAYER_TRIANGLE_DASH_COOLDOWN_MS = 260;
export const PLAYER_TRIANGLE_DASH_GROUND_CONTACT_EPSILON = 0.25;
export const PLAYER_TRIANGLE_DASH_MAX_CHARGES = 3;
export const PLAYER_TRIANGLE_CHARGES_RESTORE_DELAY_MS = 220;
export const PLAYER_TRIANGLE_FLIGHT_MAX_SECTIONS = 1;
export const PLAYER_TRIANGLE_FLIGHT_BAR_WIDTH = 220;
export const PLAYER_TRIANGLE_FLIGHT_BAR_HEIGHT = 12;
export const PLAYER_TRIANGLE_FLIGHT_BAR_SCREEN_X = 24;
export const PLAYER_TRIANGLE_FLIGHT_BAR_SCREEN_Y = 92;
export const PLAYER_MARKER_VISUAL_SCALE = 1;
export const PLAYER_MARKER_RADIUS = 4;
export const PLAYER_MARKER_FILL_COLOR = 0xffffff;
export const PLAYER_MARKER_STROKE_COLOR = 0x111111;
export const PLAYER_MARKER_STROKE_WIDTH = 2;
export const PLAYER_MARKER_IDLE_ALPHA = 0.82;
export const PLAYER_MARKER_ACTIVE_ALPHA = 0.98;

export const PLAYER_GROUND_MOVE_SPEED = 260;
export const PLAYER_GROUND_MOVE_ACCEL = 9000;
export const PLAYER_GROUND_MOVE_DECEL = 12000;
export const PLAYER_AIR_MOVE_SPEED = 240;
export const PLAYER_AIR_MOVE_ACCEL = 3600;
export const PLAYER_AIR_MOVE_DECEL = 700;
export const PLAYER_GROUNDED_DRAG_X = 120;
export const PLAYER_BALL_AIR_NO_INPUT_INERTIA_DAMPING_PER_SEC = 0.95;
export const PLAYER_BALL_BOOST_HOLD_AIR_NO_INPUT_INERTIA_DAMPING_PER_SEC = 0.5;
export const PLAYER_TRIANGLE_AIR_NO_INPUT_INERTIA_DAMPING_PER_SEC = 1.6;
export const PLAYER_SQUARE_AIR_NO_INPUT_INERTIA_DAMPING_PER_SEC = 4.8;
export const PLAYER_AIR_WIND_INFLUENCE_MULTIPLIER = 1.45;
export const PLAYER_BALL_BOOST_COOLDOWN_MS = 300;
export const PLAYER_BALL_REBOUND_MIN_APPROACH_SPEED = 520;
export const PLAYER_BALL_REBOUND_FULL_APPROACH_SPEED = 980;
export const PLAYER_BALL_REBOUND_BOOST_STRENGTH_MULTIPLIER = 1.35;
export const PLAYER_BALL_WALL_REBOUND_STEER_PERPENDICULAR_STRENGTH_MULTIPLIER = 1.8;

export let PLAYER_SQUARE_ATTACH_SURFACE_MOVE_SPEED = 220;
export let PLAYER_SQUARE_ATTACH_CONTACT_GRACE_MS = 45;
export let PLAYER_SQUARE_ATTACH_ENTRY_BUFFER_MS = 120;
export let PLAYER_SQUARE_ATTACH_ACQUIRE_RANGE_PX = 10;
export let PLAYER_SQUARE_TRAIL_RESOURCE_MAX = 100;
export let PLAYER_SQUARE_TRAIL_RESOURCE_COST_PER_UNIT = 0.2;
export let PLAYER_SQUARE_TRAIL_MANUAL_REGEN_SPEED_PX_PER_SEC = 180;
export let PLAYER_SQUARE_ATTACH_JUMP_HEIGHT_PX = 54;
export let PLAYER_SQUARE_ATTACH_JUMP_OUT_SPEED_PX_PER_SEC = 540;
export let PLAYER_SQUARE_ATTACH_JUMP_OUT_DURATION_MS = 100;
export let PLAYER_SQUARE_ATTACH_JUMP_RETURN_TIME_MS = 190;
export let PLAYER_SQUARE_ATTACH_JUMP_TETHER_STRETCH_PX = 72;
export let PLAYER_SQUARE_ATTACH_JUMP_REACQUIRE_RANGE_PX = 18;
export let PLAYER_SQUARE_ATTACH_JUMP_RELEASE_DETACH = true;
export let PLAYER_SQUARE_ROLLOVER_PREVIEW_TIME_MS = 45;
export let PLAYER_SQUARE_ROLLOVER_DURATION_MS = 170;
export let PLAYER_SQUARE_ROLLOVER_RETURN_TIME_MS = 190;
export let PLAYER_SQUARE_ROLLOVER_CORNER_DETECTION_RANGE_PX = 18;
export let PLAYER_SQUARE_ROLLOVER_SURFACE_VALIDATION_RANGE_PX = 6;

export let PLAYER_TRIANGLE_JUMP_LAUNCH_VELOCITY = -670;
export let PLAYER_TRIANGLE_JUMP_CUT_MULTIPLIER = 0.48;
export let PLAYER_TRIANGLE_JUMP_RISE_GRAVITY_SCALE = 0.72;
export let PLAYER_TRIANGLE_JUMP_APEX_GRAVITY_SCALE = 0.5;
export let PLAYER_TRIANGLE_JUMP_APEX_VELOCITY_THRESHOLD = 90;
export let PLAYER_TRIANGLE_FLIGHT_SPEED = 620;
export let PLAYER_TRIANGLE_FLIGHT_SECTION_DISTANCE_PX = 320;
export let PLAYER_TRIANGLE_FLIGHT_RESTORE_SPEED_PX_PER_SEC = 1440;
export let PLAYER_TRIANGLE_FLIGHT_TURN_SPEED_RAD_PER_SEC = Math.PI * 5.5;

export let PLAYER_MARKER_MOVE_SPEED_PX_PER_SEC = 240;
export let PLAYER_MARKER_RETURN_SPEED_PX_PER_SEC = 180;
export let PLAYER_MARKER_MAX_OFFSET_PX = 14;
export let PLAYER_MARKER_SMOOTHING_TIME_SEC = 0.08;
export let PLAYER_CAMERA_FOLLOW_LERP = 0.18;

export let PLAYER_BALL_GROUND_MOVE_SPEED = 300;
export let PLAYER_BALL_GROUND_MOVE_ACCEL = 1900;
export let PLAYER_BALL_GROUND_MOVE_DECEL = 1200;
export let PLAYER_TRIANGLE_GROUND_MOVE_SPEED = 270;
export let PLAYER_TRIANGLE_GROUND_MOVE_ACCEL = 2300;
export let PLAYER_TRIANGLE_GROUND_MOVE_DECEL = 1500;
export let PLAYER_SQUARE_GROUND_MOVE_SPEED = 235;
export let PLAYER_SQUARE_GROUND_MOVE_ACCEL = 1700;
export let PLAYER_SQUARE_GROUND_MOVE_DECEL = 1100;
export let PLAYER_BALL_AIR_MOVE_SPEED = 250;
export let PLAYER_BALL_AIR_MOVE_ACCEL = 2600;
export let PLAYER_BALL_AIR_MOVE_DECEL = 520;
export let PLAYER_TRIANGLE_AIR_MOVE_SPEED = 235;
export let PLAYER_TRIANGLE_AIR_MOVE_ACCEL = 2900;
export let PLAYER_TRIANGLE_AIR_MOVE_DECEL = 620;
export let PLAYER_SQUARE_AIR_MOVE_SPEED = 210;
export let PLAYER_SQUARE_AIR_MOVE_ACCEL = 2100;
export let PLAYER_SQUARE_AIR_MOVE_DECEL = 700;
export let PLAYER_MAX_FORM_MOVE_SPEED = 300;
export let PLAYER_AIR_WIND_RESPONSE = 5200;
export let PLAYER_AIR_WIND_MIN_DRIFT_RATIO = 0.2;
export let PLAYER_GRAVITY_Y = 1800;

export let PLAYER_BALL_JUMP_LAUNCH_VELOCITY = -620;
export let PLAYER_BALL_JUMP_CUT_MULTIPLIER = 0.45;
export let PLAYER_BALL_JUMP_RISE_GRAVITY_SCALE = 0.72;
export let PLAYER_BALL_JUMP_APEX_GRAVITY_SCALE = 0.5;
export let PLAYER_BALL_JUMP_APEX_VELOCITY_THRESHOLD = 90;
export let PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_X = 1.12;
export let PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_Y = 0.88;
export let PLAYER_BALL_ANIM_JUMP_SQUASH_DURATION_MS = 70;
export let PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_X = 0.9;
export let PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_Y = 1.12;
export let PLAYER_BALL_ANIM_JUMP_STRETCH_DURATION_MS = 90;
export let PLAYER_BALL_ANIM_JUMP_RECOVER_DURATION_MS = 130;
export let PLAYER_BALL_ANIM_LAND_IMPACT_SPEED_FOR_MAX = 900;
export let PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_X = 1.18;
export let PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_Y = 0.82;
export let PLAYER_BALL_ANIM_LAND_SQUASH_DURATION_MS = 70;
export let PLAYER_BALL_ANIM_LAND_RECOVER_DURATION_MS = 140;
export let PLAYER_BALL_ANIM_AIR_SCALE_X = 0.94;
export let PLAYER_BALL_ANIM_AIR_SCALE_Y = 1.06;
export let PLAYER_BALL_ANIM_AIR_SPEED_FOR_MAX = 700;
export let PLAYER_BALL_ANIM_AIR_SMOOTHING_TIME_SEC = 0.08;
export let PLAYER_BALL_ANIM_SWITCH_RECOVER_DURATION_MS = 150;
export let PLAYER_SQUARE_JUMP_LAUNCH_VELOCITY = -620;
export let PLAYER_SQUARE_JUMP_CUT_MULTIPLIER = 0.45;
export let PLAYER_SQUARE_JUMP_RISE_GRAVITY_SCALE = 0.72;
export let PLAYER_SQUARE_JUMP_APEX_GRAVITY_SCALE = 0.5;
export let PLAYER_SQUARE_JUMP_APEX_VELOCITY_THRESHOLD = 90;
export let PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_X = 1.0576;
export let PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_Y = 0.928;
export let PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_DURATION_MS = 65;
export let PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_X = 0.9136;
export let PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_Y = 1.1008;
export let PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_DURATION_MS = 85;
export let PLAYER_TRIANGLE_ANIM_JUMP_RECOVER_DURATION_MS = 120;
export let PLAYER_TRIANGLE_ANIM_LAND_IMPACT_SPEED_FOR_MAX = 980;
export let PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_X = 1.0936;
export let PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_Y = 0.9064;
export let PLAYER_TRIANGLE_ANIM_LAND_SQUASH_DURATION_MS = 65;
export let PLAYER_TRIANGLE_ANIM_LAND_RECOVER_DURATION_MS = 130;
export let PLAYER_TRIANGLE_ANIM_AIR_SCALE_X = 0.932;
export let PLAYER_TRIANGLE_ANIM_AIR_SCALE_Y = 1.068;
export let PLAYER_TRIANGLE_ANIM_AIR_SPEED_FOR_MAX = 820;
export let PLAYER_TRIANGLE_ANIM_AIR_SMOOTHING_TIME_SEC = 0.07;
export let PLAYER_TRIANGLE_ANIM_SWITCH_RECOVER_DURATION_MS = 128;
export let PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_X = 1.0434;
export let PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_Y = 0.9442;
export let PLAYER_SQUARE_ANIM_JUMP_SQUASH_DURATION_MS = 70;
export let PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_X = 0.9566;
export let PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_Y = 1.0496;
export let PLAYER_SQUARE_ANIM_JUMP_STRETCH_DURATION_MS = 90;
export let PLAYER_SQUARE_ANIM_JUMP_RECOVER_DURATION_MS = 130;
export let PLAYER_SQUARE_ANIM_LAND_IMPACT_SPEED_FOR_MAX = 860;
export let PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_X = 1.062;
export let PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_Y = 0.938;
export let PLAYER_SQUARE_ANIM_LAND_SQUASH_DURATION_MS = 75;
export let PLAYER_SQUARE_ANIM_LAND_RECOVER_DURATION_MS = 150;
export let PLAYER_SQUARE_ANIM_AIR_SCALE_X = 0.9768;
export let PLAYER_SQUARE_ANIM_AIR_SCALE_Y = 1.0232;
export let PLAYER_SQUARE_ANIM_AIR_SPEED_FOR_MAX = 650;
export let PLAYER_SQUARE_ANIM_AIR_SMOOTHING_TIME_SEC = 0.09;
export let PLAYER_SQUARE_ANIM_SWITCH_RECOVER_DURATION_MS = 173;

export let PLAYER_JUMP_VELOCITY = PLAYER_BALL_JUMP_LAUNCH_VELOCITY;
export let PLAYER_JUMP_CUT_MULTIPLIER = PLAYER_BALL_JUMP_CUT_MULTIPLIER;
export let PLAYER_JUMP_RISE_GRAVITY_SCALE = PLAYER_BALL_JUMP_RISE_GRAVITY_SCALE;
export let PLAYER_JUMP_APEX_GRAVITY_SCALE = PLAYER_BALL_JUMP_APEX_GRAVITY_SCALE;
export let PLAYER_JUMP_APEX_VELOCITY_THRESHOLD = PLAYER_BALL_JUMP_APEX_VELOCITY_THRESHOLD;

export let PLAYER_BALL_BOOST_SPEED = 520;
export let PLAYER_BALL_BOOST_START_IMPULSE_SPEED = 860;
export let PLAYER_BALL_BOOST_START_IMPULSE_DECAY_MS = 420;
export let PLAYER_BALL_BOOST_HOLD_MOVE_SPEED = 420;
export let PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED = 320;
export let PLAYER_BALL_BOOST_HOLD_ACCEL = 12000;
export let PLAYER_BALL_BOOST_HOLD_AIR_CONTROL_FACTOR = 0.08;
export let PLAYER_BALL_BOOST_JUMP_VELOCITY_MULTIPLIER = 1.06;
export let PLAYER_BALL_BOOST_JUMP_MIN_HORIZONTAL_SPEED = 720;
export let PLAYER_BALL_REBOUND_MIN_JUMP_VELOCITY = -700;
export let PLAYER_BALL_REBOUND_MAX_JUMP_VELOCITY = -900;
export let PLAYER_BALL_REBOUND_LANDING_WINDOW_MS = 70;
export let PLAYER_BALL_REBOUND_HIT_PAUSE_MS = 90;
export let PLAYER_BALL_REBOUND_PAUSE_BEFORE_LAUNCH_MS = 90;
export let PLAYER_BALL_REBOUND_SURFACE_INPUT_LOCK_MS = 420;
export let PLAYER_BALL_WALL_REBOUND_COYOTE_MS = 90;
export let PLAYER_BALL_WALL_REBOUND_MIN_INTO_WALL_SPEED = 160;
export let PLAYER_BALL_WALL_REBOUND_FALLBACK_UPWARD_BIAS = 0.24;
export let PLAYER_BALL_WALL_REBOUND_MIN_EXIT_SPEED = 900;
export let PLAYER_BALL_CEILING_REBOUND_MIN_EXIT_SPEED = 900;
export let PLAYER_BALL_CEILING_REBOUND_MIN_DOWNWARD_SPEED = 700;

export let PLAYER_TIMER_DEFAULT_COYOTE_MS = 110;
export let PLAYER_TIMER_DEFAULT_JUMP_BUFFER_MS = 120;
export let PLAYER_TIMER_DEFAULT_TRANSFORM_LOCK_MS = 150;
export let PLAYER_TIMER_DEFAULT_DEATH_PAUSE_MS = 250;

const refreshDerivedPlayerConstants = (): void => {
    PLAYER_SQUARE_ATTACH_JUMP_OUT_DURATION_MS = Math.max(
        1,
        Math.round((PLAYER_SQUARE_ATTACH_JUMP_HEIGHT_PX / Math.max(1, PLAYER_SQUARE_ATTACH_JUMP_OUT_SPEED_PX_PER_SEC)) * 1000)
    );
    PLAYER_MAX_FORM_MOVE_SPEED = Math.max(
        PLAYER_BALL_GROUND_MOVE_SPEED,
        PLAYER_TRIANGLE_GROUND_MOVE_SPEED,
        PLAYER_SQUARE_GROUND_MOVE_SPEED,
        PLAYER_BALL_AIR_MOVE_SPEED,
        PLAYER_TRIANGLE_AIR_MOVE_SPEED,
        PLAYER_SQUARE_AIR_MOVE_SPEED
    );
    PLAYER_BALL_BOOST_SPEED = Math.max(
        PLAYER_BALL_BOOST_HOLD_MOVE_SPEED,
        PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED,
        PLAYER_BALL_BOOST_START_IMPULSE_SPEED,
        PLAYER_BALL_BOOST_JUMP_MIN_HORIZONTAL_SPEED
    );
    PLAYER_JUMP_VELOCITY = PLAYER_BALL_JUMP_LAUNCH_VELOCITY;
    PLAYER_JUMP_CUT_MULTIPLIER = PLAYER_BALL_JUMP_CUT_MULTIPLIER;
    PLAYER_JUMP_RISE_GRAVITY_SCALE = PLAYER_BALL_JUMP_RISE_GRAVITY_SCALE;
    PLAYER_JUMP_APEX_GRAVITY_SCALE = PLAYER_BALL_JUMP_APEX_GRAVITY_SCALE;
    PLAYER_JUMP_APEX_VELOCITY_THRESHOLD = PLAYER_BALL_JUMP_APEX_VELOCITY_THRESHOLD;
};

export const applyPlayerTuningRawSnapshot = (raw: PlayerTuningRawSnapshot): void => {
    PLAYER_TIMER_DEFAULT_COYOTE_MS = raw.common.coyoteTimeMs;
    PLAYER_TIMER_DEFAULT_JUMP_BUFFER_MS = raw.common.jumpBufferMs;
    PLAYER_TIMER_DEFAULT_TRANSFORM_LOCK_MS = raw.common.transformLockMs;
    PLAYER_TIMER_DEFAULT_DEATH_PAUSE_MS = raw.common.deathPauseMs;
    PLAYER_CAMERA_FOLLOW_LERP = raw.common.cameraFollowLerp;
    PLAYER_GRAVITY_Y = raw.common.gravityY;
    PLAYER_AIR_WIND_RESPONSE = raw.common.windResponse;
    PLAYER_AIR_WIND_MIN_DRIFT_RATIO = raw.common.windMinDriftRatio;
    PLAYER_MARKER_MOVE_SPEED_PX_PER_SEC = raw.common.markerMoveSpeed;
    PLAYER_MARKER_RETURN_SPEED_PX_PER_SEC = raw.common.markerReturnSpeed;
    PLAYER_MARKER_MAX_OFFSET_PX = raw.common.markerMaxOffset;
    PLAYER_MARKER_SMOOTHING_TIME_SEC = raw.common.markerSmoothingTimeSec;

    PLAYER_BALL_GROUND_MOVE_SPEED = raw.ball.movement.groundMaxSpeed;
    PLAYER_BALL_GROUND_MOVE_ACCEL = raw.ball.movement.groundAccel;
    PLAYER_BALL_GROUND_MOVE_DECEL = raw.ball.movement.groundDecel;
    PLAYER_BALL_AIR_MOVE_SPEED = raw.ball.movement.airMaxSpeed;
    PLAYER_BALL_AIR_MOVE_ACCEL = raw.ball.movement.airAccel;
    PLAYER_BALL_AIR_MOVE_DECEL = raw.ball.movement.airDecel;
    PLAYER_BALL_JUMP_LAUNCH_VELOCITY = raw.ball.jump.launchVelocity;
    PLAYER_BALL_JUMP_CUT_MULTIPLIER = raw.ball.jump.jumpCutMultiplier;
    PLAYER_BALL_JUMP_RISE_GRAVITY_SCALE = raw.ball.jump.riseGravityScale;
    PLAYER_BALL_JUMP_APEX_GRAVITY_SCALE = raw.ball.jump.apexGravityScale;
    PLAYER_BALL_JUMP_APEX_VELOCITY_THRESHOLD = raw.ball.jump.apexVelocityThreshold;
    PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_X = raw.ball.animation.jumpSquashScaleX;
    PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_Y = raw.ball.animation.jumpSquashScaleY;
    PLAYER_BALL_ANIM_JUMP_SQUASH_DURATION_MS = raw.ball.animation.jumpSquashDurationMs;
    PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_X = raw.ball.animation.jumpStretchScaleX;
    PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_Y = raw.ball.animation.jumpStretchScaleY;
    PLAYER_BALL_ANIM_JUMP_STRETCH_DURATION_MS = raw.ball.animation.jumpStretchDurationMs;
    PLAYER_BALL_ANIM_JUMP_RECOVER_DURATION_MS = raw.ball.animation.jumpRecoverDurationMs;
    PLAYER_BALL_ANIM_LAND_IMPACT_SPEED_FOR_MAX = raw.ball.animation.landImpactSpeedForMax;
    PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_X = raw.ball.animation.landSquashScaleX;
    PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_Y = raw.ball.animation.landSquashScaleY;
    PLAYER_BALL_ANIM_LAND_SQUASH_DURATION_MS = raw.ball.animation.landSquashDurationMs;
    PLAYER_BALL_ANIM_LAND_RECOVER_DURATION_MS = raw.ball.animation.landRecoverDurationMs;
    PLAYER_BALL_ANIM_AIR_SCALE_X = raw.ball.animation.airScaleX;
    PLAYER_BALL_ANIM_AIR_SCALE_Y = raw.ball.animation.airScaleY;
    PLAYER_BALL_ANIM_AIR_SPEED_FOR_MAX = raw.ball.animation.airSpeedForMax;
    PLAYER_BALL_ANIM_AIR_SMOOTHING_TIME_SEC = raw.ball.animation.airSmoothingTimeSec;
    PLAYER_BALL_ANIM_SWITCH_RECOVER_DURATION_MS = raw.ball.animation.switchRecoverDurationMs;
    PLAYER_BALL_BOOST_START_IMPULSE_SPEED = raw.ball.boost.startImpulseSpeed;
    PLAYER_BALL_BOOST_START_IMPULSE_DECAY_MS = raw.ball.boost.startImpulseDecayMs;
    PLAYER_BALL_BOOST_HOLD_MOVE_SPEED = raw.ball.boost.holdGroundMoveSpeed;
    PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED = raw.ball.boost.holdAirMoveSpeed;
    PLAYER_BALL_BOOST_HOLD_ACCEL = raw.ball.boost.holdAccel;
    PLAYER_BALL_BOOST_JUMP_MIN_HORIZONTAL_SPEED = raw.ball.boost.jumpMinHorizontalSpeed;
    PLAYER_BALL_BOOST_JUMP_VELOCITY_MULTIPLIER = raw.ball.boost.jumpVelocityMultiplier;
    PLAYER_BALL_BOOST_HOLD_AIR_CONTROL_FACTOR = raw.ball.boost.holdAirControlFactor;
    PLAYER_BALL_REBOUND_LANDING_WINDOW_MS = raw.ball.rebound.inputWindowMs;
    PLAYER_BALL_REBOUND_HIT_PAUSE_MS = raw.ball.rebound.hitPauseMs;
    PLAYER_BALL_REBOUND_MIN_JUMP_VELOCITY = raw.ball.rebound.level1JumpVelocity;
    PLAYER_BALL_REBOUND_MAX_JUMP_VELOCITY = raw.ball.rebound.level2JumpVelocity;
    PLAYER_BALL_WALL_REBOUND_COYOTE_MS = raw.ball.rebound.wallCoyoteMs;
    PLAYER_BALL_REBOUND_PAUSE_BEFORE_LAUNCH_MS = raw.ball.rebound.pauseBeforeLaunchMs;
    PLAYER_BALL_REBOUND_SURFACE_INPUT_LOCK_MS = raw.ball.rebound.surfaceInputLockMs;
    PLAYER_BALL_WALL_REBOUND_MIN_INTO_WALL_SPEED = raw.ball.rebound.wallMinIntoSurfaceSpeed;
    PLAYER_BALL_WALL_REBOUND_FALLBACK_UPWARD_BIAS = raw.ball.rebound.wallFallbackUpwardBias;
    PLAYER_BALL_WALL_REBOUND_MIN_EXIT_SPEED = raw.ball.rebound.wallMinExitSpeed;
    PLAYER_BALL_CEILING_REBOUND_MIN_EXIT_SPEED = raw.ball.rebound.ceilingMinExitSpeed;
    PLAYER_BALL_CEILING_REBOUND_MIN_DOWNWARD_SPEED = raw.ball.rebound.ceilingMinDownwardSpeed;

    PLAYER_TRIANGLE_GROUND_MOVE_SPEED = raw.triangle.movement.groundMaxSpeed;
    PLAYER_TRIANGLE_GROUND_MOVE_ACCEL = raw.triangle.movement.groundAccel;
    PLAYER_TRIANGLE_GROUND_MOVE_DECEL = raw.triangle.movement.groundDecel;
    PLAYER_TRIANGLE_AIR_MOVE_SPEED = raw.triangle.movement.airMaxSpeed;
    PLAYER_TRIANGLE_AIR_MOVE_ACCEL = raw.triangle.movement.airAccel;
    PLAYER_TRIANGLE_AIR_MOVE_DECEL = raw.triangle.movement.airDecel;
    PLAYER_TRIANGLE_JUMP_LAUNCH_VELOCITY = raw.triangle.jump.launchVelocity;
    PLAYER_TRIANGLE_JUMP_CUT_MULTIPLIER = raw.triangle.jump.jumpCutMultiplier;
    PLAYER_TRIANGLE_JUMP_RISE_GRAVITY_SCALE = raw.triangle.jump.riseGravityScale;
    PLAYER_TRIANGLE_JUMP_APEX_GRAVITY_SCALE = raw.triangle.jump.apexGravityScale;
    PLAYER_TRIANGLE_JUMP_APEX_VELOCITY_THRESHOLD = raw.triangle.jump.apexVelocityThreshold;
    PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_X = raw.triangle.animation.jumpSquashScaleX;
    PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_Y = raw.triangle.animation.jumpSquashScaleY;
    PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_DURATION_MS = raw.triangle.animation.jumpSquashDurationMs;
    PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_X = raw.triangle.animation.jumpStretchScaleX;
    PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_Y = raw.triangle.animation.jumpStretchScaleY;
    PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_DURATION_MS = raw.triangle.animation.jumpStretchDurationMs;
    PLAYER_TRIANGLE_ANIM_JUMP_RECOVER_DURATION_MS = raw.triangle.animation.jumpRecoverDurationMs;
    PLAYER_TRIANGLE_ANIM_LAND_IMPACT_SPEED_FOR_MAX = raw.triangle.animation.landImpactSpeedForMax;
    PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_X = raw.triangle.animation.landSquashScaleX;
    PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_Y = raw.triangle.animation.landSquashScaleY;
    PLAYER_TRIANGLE_ANIM_LAND_SQUASH_DURATION_MS = raw.triangle.animation.landSquashDurationMs;
    PLAYER_TRIANGLE_ANIM_LAND_RECOVER_DURATION_MS = raw.triangle.animation.landRecoverDurationMs;
    PLAYER_TRIANGLE_ANIM_AIR_SCALE_X = raw.triangle.animation.airScaleX;
    PLAYER_TRIANGLE_ANIM_AIR_SCALE_Y = raw.triangle.animation.airScaleY;
    PLAYER_TRIANGLE_ANIM_AIR_SPEED_FOR_MAX = raw.triangle.animation.airSpeedForMax;
    PLAYER_TRIANGLE_ANIM_AIR_SMOOTHING_TIME_SEC = raw.triangle.animation.airSmoothingTimeSec;
    PLAYER_TRIANGLE_ANIM_SWITCH_RECOVER_DURATION_MS = raw.triangle.animation.switchRecoverDurationMs;
    PLAYER_TRIANGLE_FLIGHT_SPEED = raw.triangle.flight.flightSpeed;
    PLAYER_TRIANGLE_FLIGHT_SECTION_DISTANCE_PX = raw.triangle.flight.flightDistancePx;
    PLAYER_TRIANGLE_FLIGHT_RESTORE_SPEED_PX_PER_SEC = raw.triangle.flight.flightRestoreSpeed;
    PLAYER_TRIANGLE_FLIGHT_TURN_SPEED_RAD_PER_SEC = raw.triangle.flight.flightTurnSpeedRadPerSec;

    PLAYER_SQUARE_GROUND_MOVE_SPEED = raw.square.movement.groundMaxSpeed;
    PLAYER_SQUARE_GROUND_MOVE_ACCEL = raw.square.movement.groundAccel;
    PLAYER_SQUARE_GROUND_MOVE_DECEL = raw.square.movement.groundDecel;
    PLAYER_SQUARE_AIR_MOVE_SPEED = raw.square.movement.airMaxSpeed;
    PLAYER_SQUARE_AIR_MOVE_ACCEL = raw.square.movement.airAccel;
    PLAYER_SQUARE_AIR_MOVE_DECEL = raw.square.movement.airDecel;
    PLAYER_SQUARE_JUMP_LAUNCH_VELOCITY = raw.square.jump.launchVelocity;
    PLAYER_SQUARE_JUMP_CUT_MULTIPLIER = raw.square.jump.jumpCutMultiplier;
    PLAYER_SQUARE_JUMP_RISE_GRAVITY_SCALE = raw.square.jump.riseGravityScale;
    PLAYER_SQUARE_JUMP_APEX_GRAVITY_SCALE = raw.square.jump.apexGravityScale;
    PLAYER_SQUARE_JUMP_APEX_VELOCITY_THRESHOLD = raw.square.jump.apexVelocityThreshold;
    PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_X = raw.square.animation.jumpSquashScaleX;
    PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_Y = raw.square.animation.jumpSquashScaleY;
    PLAYER_SQUARE_ANIM_JUMP_SQUASH_DURATION_MS = raw.square.animation.jumpSquashDurationMs;
    PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_X = raw.square.animation.jumpStretchScaleX;
    PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_Y = raw.square.animation.jumpStretchScaleY;
    PLAYER_SQUARE_ANIM_JUMP_STRETCH_DURATION_MS = raw.square.animation.jumpStretchDurationMs;
    PLAYER_SQUARE_ANIM_JUMP_RECOVER_DURATION_MS = raw.square.animation.jumpRecoverDurationMs;
    PLAYER_SQUARE_ANIM_LAND_IMPACT_SPEED_FOR_MAX = raw.square.animation.landImpactSpeedForMax;
    PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_X = raw.square.animation.landSquashScaleX;
    PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_Y = raw.square.animation.landSquashScaleY;
    PLAYER_SQUARE_ANIM_LAND_SQUASH_DURATION_MS = raw.square.animation.landSquashDurationMs;
    PLAYER_SQUARE_ANIM_LAND_RECOVER_DURATION_MS = raw.square.animation.landRecoverDurationMs;
    PLAYER_SQUARE_ANIM_AIR_SCALE_X = raw.square.animation.airScaleX;
    PLAYER_SQUARE_ANIM_AIR_SCALE_Y = raw.square.animation.airScaleY;
    PLAYER_SQUARE_ANIM_AIR_SPEED_FOR_MAX = raw.square.animation.airSpeedForMax;
    PLAYER_SQUARE_ANIM_AIR_SMOOTHING_TIME_SEC = raw.square.animation.airSmoothingTimeSec;
    PLAYER_SQUARE_ANIM_SWITCH_RECOVER_DURATION_MS = raw.square.animation.switchRecoverDurationMs;
    PLAYER_SQUARE_ATTACH_ACQUIRE_RANGE_PX = raw.square.attach.acquireRangePx;
    PLAYER_SQUARE_ATTACH_ENTRY_BUFFER_MS = raw.square.attach.attachBufferMs;
    PLAYER_SQUARE_ATTACH_CONTACT_GRACE_MS = raw.square.attach.contactGraceMs;
    PLAYER_SQUARE_ATTACH_SURFACE_MOVE_SPEED = raw.square.attach.surfaceMoveSpeed;
    PLAYER_SQUARE_TRAIL_RESOURCE_MAX = raw.square.trail.resourceMax;
    PLAYER_SQUARE_TRAIL_RESOURCE_COST_PER_UNIT = raw.square.trail.spendPerPx;
    PLAYER_SQUARE_TRAIL_MANUAL_REGEN_SPEED_PX_PER_SEC = raw.square.trail.manualRegenSpeed;
    PLAYER_SQUARE_ATTACH_JUMP_HEIGHT_PX = raw.square.attachJump.heightPx;
    PLAYER_SQUARE_ATTACH_JUMP_OUT_SPEED_PX_PER_SEC = raw.square.attachJump.outSpeed;
    PLAYER_SQUARE_ATTACH_JUMP_RETURN_TIME_MS = raw.square.attachJump.returnTimeMs;
    PLAYER_SQUARE_ATTACH_JUMP_TETHER_STRETCH_PX = raw.square.attachJump.tetherStretchPx;
    PLAYER_SQUARE_ATTACH_JUMP_REACQUIRE_RANGE_PX = raw.square.attachJump.reacquireRangePx;
    PLAYER_SQUARE_ROLLOVER_PREVIEW_TIME_MS = raw.square.rollover.previewTimeMs;
    PLAYER_SQUARE_ROLLOVER_DURATION_MS = raw.square.rollover.durationMs;
    PLAYER_SQUARE_ROLLOVER_RETURN_TIME_MS = raw.square.rollover.returnTimeMs;
    PLAYER_SQUARE_ROLLOVER_CORNER_DETECTION_RANGE_PX = raw.square.rollover.cornerDetectionRangePx;
    PLAYER_SQUARE_ROLLOVER_SURFACE_VALIDATION_RANGE_PX = raw.square.rollover.surfaceValidationRangePx;

    refreshDerivedPlayerConstants();
};

export const capturePlayerTuningRawSnapshot = (): PlayerTuningRawSnapshot => ({
    common: {
        coyoteTimeMs: PLAYER_TIMER_DEFAULT_COYOTE_MS,
        jumpBufferMs: PLAYER_TIMER_DEFAULT_JUMP_BUFFER_MS,
        transformLockMs: PLAYER_TIMER_DEFAULT_TRANSFORM_LOCK_MS,
        deathPauseMs: PLAYER_TIMER_DEFAULT_DEATH_PAUSE_MS,
        cameraFollowLerp: PLAYER_CAMERA_FOLLOW_LERP,
        gravityY: PLAYER_GRAVITY_Y,
        windResponse: PLAYER_AIR_WIND_RESPONSE,
        windMinDriftRatio: PLAYER_AIR_WIND_MIN_DRIFT_RATIO,
        markerMoveSpeed: PLAYER_MARKER_MOVE_SPEED_PX_PER_SEC,
        markerReturnSpeed: PLAYER_MARKER_RETURN_SPEED_PX_PER_SEC,
        markerMaxOffset: PLAYER_MARKER_MAX_OFFSET_PX,
        markerSmoothingTimeSec: PLAYER_MARKER_SMOOTHING_TIME_SEC
    },
    ball: {
        movement: {
            groundMaxSpeed: PLAYER_BALL_GROUND_MOVE_SPEED,
            groundAccel: PLAYER_BALL_GROUND_MOVE_ACCEL,
            groundDecel: PLAYER_BALL_GROUND_MOVE_DECEL,
            airMaxSpeed: PLAYER_BALL_AIR_MOVE_SPEED,
            airAccel: PLAYER_BALL_AIR_MOVE_ACCEL,
            airDecel: PLAYER_BALL_AIR_MOVE_DECEL
        },
        jump: {
            launchVelocity: PLAYER_BALL_JUMP_LAUNCH_VELOCITY,
            jumpCutMultiplier: PLAYER_BALL_JUMP_CUT_MULTIPLIER,
            riseGravityScale: PLAYER_BALL_JUMP_RISE_GRAVITY_SCALE,
            apexGravityScale: PLAYER_BALL_JUMP_APEX_GRAVITY_SCALE,
            apexVelocityThreshold: PLAYER_BALL_JUMP_APEX_VELOCITY_THRESHOLD
        },
        animation: {
            jumpSquashScaleX: PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_X,
            jumpSquashScaleY: PLAYER_BALL_ANIM_JUMP_SQUASH_SCALE_Y,
            jumpSquashDurationMs: PLAYER_BALL_ANIM_JUMP_SQUASH_DURATION_MS,
            jumpStretchScaleX: PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_X,
            jumpStretchScaleY: PLAYER_BALL_ANIM_JUMP_STRETCH_SCALE_Y,
            jumpStretchDurationMs: PLAYER_BALL_ANIM_JUMP_STRETCH_DURATION_MS,
            jumpRecoverDurationMs: PLAYER_BALL_ANIM_JUMP_RECOVER_DURATION_MS,
            landImpactSpeedForMax: PLAYER_BALL_ANIM_LAND_IMPACT_SPEED_FOR_MAX,
            landSquashScaleX: PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_X,
            landSquashScaleY: PLAYER_BALL_ANIM_LAND_SQUASH_SCALE_Y,
            landSquashDurationMs: PLAYER_BALL_ANIM_LAND_SQUASH_DURATION_MS,
            landRecoverDurationMs: PLAYER_BALL_ANIM_LAND_RECOVER_DURATION_MS,
            airScaleX: PLAYER_BALL_ANIM_AIR_SCALE_X,
            airScaleY: PLAYER_BALL_ANIM_AIR_SCALE_Y,
            airSpeedForMax: PLAYER_BALL_ANIM_AIR_SPEED_FOR_MAX,
            airSmoothingTimeSec: PLAYER_BALL_ANIM_AIR_SMOOTHING_TIME_SEC,
            switchRecoverDurationMs: PLAYER_BALL_ANIM_SWITCH_RECOVER_DURATION_MS
        },
        boost: {
            startImpulseSpeed: PLAYER_BALL_BOOST_START_IMPULSE_SPEED,
            startImpulseDecayMs: PLAYER_BALL_BOOST_START_IMPULSE_DECAY_MS,
            holdGroundMoveSpeed: PLAYER_BALL_BOOST_HOLD_MOVE_SPEED,
            holdAirMoveSpeed: PLAYER_BALL_BOOST_HOLD_AIR_MOVE_SPEED,
            holdAccel: PLAYER_BALL_BOOST_HOLD_ACCEL,
            jumpMinHorizontalSpeed: PLAYER_BALL_BOOST_JUMP_MIN_HORIZONTAL_SPEED,
            jumpVelocityMultiplier: PLAYER_BALL_BOOST_JUMP_VELOCITY_MULTIPLIER,
            holdAirControlFactor: PLAYER_BALL_BOOST_HOLD_AIR_CONTROL_FACTOR
        },
        rebound: {
            inputWindowMs: PLAYER_BALL_REBOUND_LANDING_WINDOW_MS,
            hitPauseMs: PLAYER_BALL_REBOUND_HIT_PAUSE_MS,
            level1JumpVelocity: PLAYER_BALL_REBOUND_MIN_JUMP_VELOCITY,
            level2JumpVelocity: PLAYER_BALL_REBOUND_MAX_JUMP_VELOCITY,
            wallCoyoteMs: PLAYER_BALL_WALL_REBOUND_COYOTE_MS,
            pauseBeforeLaunchMs: PLAYER_BALL_REBOUND_PAUSE_BEFORE_LAUNCH_MS,
            surfaceInputLockMs: PLAYER_BALL_REBOUND_SURFACE_INPUT_LOCK_MS,
            wallMinIntoSurfaceSpeed: PLAYER_BALL_WALL_REBOUND_MIN_INTO_WALL_SPEED,
            wallFallbackUpwardBias: PLAYER_BALL_WALL_REBOUND_FALLBACK_UPWARD_BIAS,
            wallMinExitSpeed: PLAYER_BALL_WALL_REBOUND_MIN_EXIT_SPEED,
            ceilingMinExitSpeed: PLAYER_BALL_CEILING_REBOUND_MIN_EXIT_SPEED,
            ceilingMinDownwardSpeed: PLAYER_BALL_CEILING_REBOUND_MIN_DOWNWARD_SPEED
        }
    },
    triangle: {
        movement: {
            groundMaxSpeed: PLAYER_TRIANGLE_GROUND_MOVE_SPEED,
            groundAccel: PLAYER_TRIANGLE_GROUND_MOVE_ACCEL,
            groundDecel: PLAYER_TRIANGLE_GROUND_MOVE_DECEL,
            airMaxSpeed: PLAYER_TRIANGLE_AIR_MOVE_SPEED,
            airAccel: PLAYER_TRIANGLE_AIR_MOVE_ACCEL,
            airDecel: PLAYER_TRIANGLE_AIR_MOVE_DECEL
        },
        jump: {
            launchVelocity: PLAYER_TRIANGLE_JUMP_LAUNCH_VELOCITY,
            jumpCutMultiplier: PLAYER_TRIANGLE_JUMP_CUT_MULTIPLIER,
            riseGravityScale: PLAYER_TRIANGLE_JUMP_RISE_GRAVITY_SCALE,
            apexGravityScale: PLAYER_TRIANGLE_JUMP_APEX_GRAVITY_SCALE,
            apexVelocityThreshold: PLAYER_TRIANGLE_JUMP_APEX_VELOCITY_THRESHOLD
        },
        animation: {
            jumpSquashScaleX: PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_X,
            jumpSquashScaleY: PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_SCALE_Y,
            jumpSquashDurationMs: PLAYER_TRIANGLE_ANIM_JUMP_SQUASH_DURATION_MS,
            jumpStretchScaleX: PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_X,
            jumpStretchScaleY: PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_SCALE_Y,
            jumpStretchDurationMs: PLAYER_TRIANGLE_ANIM_JUMP_STRETCH_DURATION_MS,
            jumpRecoverDurationMs: PLAYER_TRIANGLE_ANIM_JUMP_RECOVER_DURATION_MS,
            landImpactSpeedForMax: PLAYER_TRIANGLE_ANIM_LAND_IMPACT_SPEED_FOR_MAX,
            landSquashScaleX: PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_X,
            landSquashScaleY: PLAYER_TRIANGLE_ANIM_LAND_SQUASH_SCALE_Y,
            landSquashDurationMs: PLAYER_TRIANGLE_ANIM_LAND_SQUASH_DURATION_MS,
            landRecoverDurationMs: PLAYER_TRIANGLE_ANIM_LAND_RECOVER_DURATION_MS,
            airScaleX: PLAYER_TRIANGLE_ANIM_AIR_SCALE_X,
            airScaleY: PLAYER_TRIANGLE_ANIM_AIR_SCALE_Y,
            airSpeedForMax: PLAYER_TRIANGLE_ANIM_AIR_SPEED_FOR_MAX,
            airSmoothingTimeSec: PLAYER_TRIANGLE_ANIM_AIR_SMOOTHING_TIME_SEC,
            switchRecoverDurationMs: PLAYER_TRIANGLE_ANIM_SWITCH_RECOVER_DURATION_MS
        },
        flight: {
            flightSpeed: PLAYER_TRIANGLE_FLIGHT_SPEED,
            flightDistancePx: PLAYER_TRIANGLE_FLIGHT_SECTION_DISTANCE_PX,
            flightRestoreSpeed: PLAYER_TRIANGLE_FLIGHT_RESTORE_SPEED_PX_PER_SEC,
            flightTurnSpeedRadPerSec: PLAYER_TRIANGLE_FLIGHT_TURN_SPEED_RAD_PER_SEC
        }
    },
    square: {
        movement: {
            groundMaxSpeed: PLAYER_SQUARE_GROUND_MOVE_SPEED,
            groundAccel: PLAYER_SQUARE_GROUND_MOVE_ACCEL,
            groundDecel: PLAYER_SQUARE_GROUND_MOVE_DECEL,
            airMaxSpeed: PLAYER_SQUARE_AIR_MOVE_SPEED,
            airAccel: PLAYER_SQUARE_AIR_MOVE_ACCEL,
            airDecel: PLAYER_SQUARE_AIR_MOVE_DECEL
        },
        jump: {
            launchVelocity: PLAYER_SQUARE_JUMP_LAUNCH_VELOCITY,
            jumpCutMultiplier: PLAYER_SQUARE_JUMP_CUT_MULTIPLIER,
            riseGravityScale: PLAYER_SQUARE_JUMP_RISE_GRAVITY_SCALE,
            apexGravityScale: PLAYER_SQUARE_JUMP_APEX_GRAVITY_SCALE,
            apexVelocityThreshold: PLAYER_SQUARE_JUMP_APEX_VELOCITY_THRESHOLD
        },
        animation: {
            jumpSquashScaleX: PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_X,
            jumpSquashScaleY: PLAYER_SQUARE_ANIM_JUMP_SQUASH_SCALE_Y,
            jumpSquashDurationMs: PLAYER_SQUARE_ANIM_JUMP_SQUASH_DURATION_MS,
            jumpStretchScaleX: PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_X,
            jumpStretchScaleY: PLAYER_SQUARE_ANIM_JUMP_STRETCH_SCALE_Y,
            jumpStretchDurationMs: PLAYER_SQUARE_ANIM_JUMP_STRETCH_DURATION_MS,
            jumpRecoverDurationMs: PLAYER_SQUARE_ANIM_JUMP_RECOVER_DURATION_MS,
            landImpactSpeedForMax: PLAYER_SQUARE_ANIM_LAND_IMPACT_SPEED_FOR_MAX,
            landSquashScaleX: PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_X,
            landSquashScaleY: PLAYER_SQUARE_ANIM_LAND_SQUASH_SCALE_Y,
            landSquashDurationMs: PLAYER_SQUARE_ANIM_LAND_SQUASH_DURATION_MS,
            landRecoverDurationMs: PLAYER_SQUARE_ANIM_LAND_RECOVER_DURATION_MS,
            airScaleX: PLAYER_SQUARE_ANIM_AIR_SCALE_X,
            airScaleY: PLAYER_SQUARE_ANIM_AIR_SCALE_Y,
            airSpeedForMax: PLAYER_SQUARE_ANIM_AIR_SPEED_FOR_MAX,
            airSmoothingTimeSec: PLAYER_SQUARE_ANIM_AIR_SMOOTHING_TIME_SEC,
            switchRecoverDurationMs: PLAYER_SQUARE_ANIM_SWITCH_RECOVER_DURATION_MS
        },
        attach: {
            acquireRangePx: PLAYER_SQUARE_ATTACH_ACQUIRE_RANGE_PX,
            attachBufferMs: PLAYER_SQUARE_ATTACH_ENTRY_BUFFER_MS,
            contactGraceMs: PLAYER_SQUARE_ATTACH_CONTACT_GRACE_MS,
            surfaceMoveSpeed: PLAYER_SQUARE_ATTACH_SURFACE_MOVE_SPEED
        },
        trail: {
            resourceMax: PLAYER_SQUARE_TRAIL_RESOURCE_MAX,
            spendPerPx: PLAYER_SQUARE_TRAIL_RESOURCE_COST_PER_UNIT,
            manualRegenSpeed: PLAYER_SQUARE_TRAIL_MANUAL_REGEN_SPEED_PX_PER_SEC
        },
        attachJump: {
            heightPx: PLAYER_SQUARE_ATTACH_JUMP_HEIGHT_PX,
            outSpeed: PLAYER_SQUARE_ATTACH_JUMP_OUT_SPEED_PX_PER_SEC,
            returnTimeMs: PLAYER_SQUARE_ATTACH_JUMP_RETURN_TIME_MS,
            tetherStretchPx: PLAYER_SQUARE_ATTACH_JUMP_TETHER_STRETCH_PX,
            reacquireRangePx: PLAYER_SQUARE_ATTACH_JUMP_REACQUIRE_RANGE_PX
        },
        rollover: {
            previewTimeMs: PLAYER_SQUARE_ROLLOVER_PREVIEW_TIME_MS,
            durationMs: PLAYER_SQUARE_ROLLOVER_DURATION_MS,
            returnTimeMs: PLAYER_SQUARE_ROLLOVER_RETURN_TIME_MS,
            cornerDetectionRangePx: PLAYER_SQUARE_ROLLOVER_CORNER_DETECTION_RANGE_PX,
            surfaceValidationRangePx: PLAYER_SQUARE_ROLLOVER_SURFACE_VALIDATION_RANGE_PX
        }
    }
});

refreshDerivedPlayerConstants();
